### ISSUE TITLE
Document utterances without assertions

### ISSUE THREAD

**Issue by dmarvp** [bespoken/bespoken-docs#87]
### Description
Both for unit testing and end to end testing we give the possibility to our users of including an utterance without an assertion like this:

```yaml
----
- test: Launch and ask for help
- open guess the price
- help: How can I help you?
```
However, this is not documented anywhere in our docs. We should include it and explain the reasoning behind it.
